#open-circuit and short-circuit test GUI
#RollNo. - 120EE0462
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit,QLabel,QApplication
from PyQt5.QtCore import QRect, center
from PyQt5.QtGui import QDoubleValidator,QFont
class Ui_Dialog(object):
    def close(self):
        self.close()  
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 670)
        Dialog.setWindowTitle("OC and SC test of Transformer")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(180, 160, 120, 25))
        self.lineEdit.setObjectName("line edit")
        onlyint = QDoubleValidator()
        self.lineEdit.setValidator(onlyint)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 60, 221, 41))
        self.label.setStyleSheet("\n"
"font: 14pt \"Arial\";")
        self.label.setText("Open-Circuit Test Results")
        self.label.setWordWrap(True)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(420, 60, 250, 41))
        self.label_3.setStyleSheet("\n"
"font: 14pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.label_3.setText("Short-Circuit Test Results")
        self.label_3.setWordWrap(True)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 200, 41))
        self.label_4.setStyleSheet("font: 10pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.label_4.setText("Wattmeter Reading")
        self.label_4.setWordWrap(True) 
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 121, 120, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        onlyint = QDoubleValidator()
        self.lineEdit_3.setValidator(onlyint)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 150, 200, 41))
        self.label_5.setStyleSheet("font: 10pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.label_5.setText("Voltmeter Reading")
        self.label_5.setWordWrap(True) 
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 200, 41))
        self.label_6.setStyleSheet("font: 10pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.label_6.setText("Ammeter Reading")
        self.label_6.setWordWrap(True) 
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 200, 120, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        onlyint = QDoubleValidator()
        self.lineEdit_4.setValidator(onlyint)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(390, 110, 200, 41))
        self.label_7.setStyleSheet("font: 10pt \"Arial\";")
        self.label_7.setObjectName("label_7")
        self.label_7.setText("Wattmeter Reading")
        self.label_7.setWordWrap(True) 
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(390, 150, 111, 41))
        self.label_8.setStyleSheet("font: 10pt \"Arial\";")
        self.label_8.setObjectName("label_8")
        self.label_8.setText("Voltmeter Reading")
        self.label_8.setWordWrap(True) 
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(390, 190, 111, 41))
        self.label_9.setStyleSheet("font: 10pt \"Arial\";")
        self.label_9.setObjectName("label_9")
        self.label_9.setText("Ammeter Reading")
        self.label_9.setWordWrap(True)
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(530, 160, 120, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        onlyint = QDoubleValidator()
        self.lineEdit_5.setValidator(onlyint)
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(530, 200, 120, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        onlyint = QDoubleValidator()
        self.lineEdit_6.setValidator(onlyint)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(530, 120, 120, 25))
        self.lineEdit_2.setObjectName("lineEdit_2") 
        onlyint = QDoubleValidator()  
        self.lineEdit_2.setValidator(onlyint)
        self.labelres_1 = QtWidgets.QLabel(Dialog)
        self.labelres_1.setGeometry(QtCore.QRect(20, 290, 330, 300))
        self.labelres_1.setObjectName("labelres_1") 
        self.labelres_1.setWordWrap(True)
        self.labelres_1.setFont(QFont('Arial',12))
        self.labelres_1.setStyleSheet("QLabel"
                               "{"
								"border : 1.5px solid black;"
								"background : cyan;"
								"}")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 250, 155, 26))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("View Parameters")
        self.pushButton.clicked.connect(self.ocr)
        self.labelres_2 = QtWidgets.QLabel(Dialog)
        self.labelres_2.setGeometry(QtCore.QRect(370, 290, 320, 300))
        self.labelres_2.setObjectName("labelres_2")
        self.labelres_2.setWordWrap(True)
        self.labelres_2.setFont(QFont('Arial',12))
        self.labelres_2.setStyleSheet("QLabel"
                               "{"
								"border : 1.5px solid black;"
								"background : cyan;"
								"}")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 250, 151, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setText("View Parameters")
        self.pushButton_2.clicked.connect(self.scr)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 620, 75, 26))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setText("EXIT")
        self.pushButton_3.clicked.connect(self.close)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(250, 5, 350, 41))
        self.label_10.setStyleSheet("font: 18pt \"Arial\";")
        self.label_10.setObjectName("label_10")
        self.label_10.setText("OC AND SC TEST ")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(220, 32, 350, 41))
        self.label_11.setStyleSheet("font: 10pt \"Bookman Old Script\";")
        self.label_11.setObjectName("label_11")
        self.label_11.setText("(NOTE: Please use S.I. unit for input values)")
    
    def ocr(self):
        W0 = float(self.lineEdit_3.text())
        I0 = float(self.lineEdit_4.text())
        V0 = float(self.lineEdit.text())
        pf = W0/(V0*I0)
        Iw = W0/V0
        Im = pow(pow(I0,2) - pow(Iw,2),1/2)
        self.labelres_1.setText("F.L Iron Loss = "+ str(W0) + " Watt"+"\n" + "\r\nNo load p.f = " + str(pf) + "\n" + "\n Iw = " + str((Iw)) +" A"+ "\n"+"\n Im = " + str(Im) + " A"+"\n" + "\n Equivalent Exciting Resistance,R0 = " + str(V0/Iw) + " Ohm"+"\n"+"\n Equivalent Exciting Reactance,X0 = " + str(V0/Im)+" Ohm")
    def scr(self):
        Wc = float(self.lineEdit_2.text())
        Ic = float(self.lineEdit_6.text())
        Vc = float(self.lineEdit_5.text())
        pfc= Wc/(Vc*Ic)
        Rc = Wc/pow(Ic,2)
        Zc = Vc/Ic
        Xc = pow(pow(Zc,2) - pow(Rc,2),1/2)
        self.labelres_2.setText("F.L Copper Loss = "+ str(Wc) + " Watt"+ "\n" "\nShort-circuit p.f = " + str(pfc)+ "\n"+"\nEquivalent Resistance(ref to H.V. side) = " + str(Rc)+" Ohm"+"\n"+ "\nEquivalent Impedence(ref. to H.V side),Zc = " + str(Vc/Ic) +" Ohm"+ "\n"+ "\nEquivalent Reactance(ref. to H.V. side),Xc = " + str(Xc)+" Ohm")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
